/**
 * AI Theme Generator Tool
 *
 * AI-powered theme generation integrated into the Tools tab.
 * Uses chat interface to generate complete color palettes from descriptions.
 */

import { useState, useCallback } from 'react';
import { Sparkles, RefreshCw } from 'lucide-react';
import { useAIChat } from '../../hooks/useAIChat';
import { useDesignManagerContext } from '../../context/DesignManagerContext';
import { AIChat } from '../ai/AIChat';

/**
 * Suggested prompts for quick generation
 */
const QUICK_PROMPTS = [
  'Warm and cozy with earthy tones',
  'Modern minimal with cool blue',
  'Professional dark SaaS theme',
  'Soft pastel wellness vibe',
  'High-contrast accessible purple',
];

export function AIThemeGenerator({ onClose }) {
  const { importTheme, apiKey, apiEndpoint } = useDesignManagerContext();
  const [pendingTheme, setPendingTheme] = useState(null);

  /**
   * Handle theme application from AI response
   */
  const handleApplyTheme = useCallback((theme) => {
    if (!theme?.light || !theme?.dark) return;

    const themeData = {
      colors: {
        light: theme.light,
        dark: theme.dark,
      },
    };

    importTheme(themeData);
    setPendingTheme(null);
  }, [importTheme]);

  /**
   * Handle theme generated by AI (for preview)
   */
  const handleThemeGenerated = useCallback((theme) => {
    setPendingTheme(theme);
  }, []);

  const {
    messages,
    isLoading,
    sendMessage,
    clearMessages,
    hasApiKey,
  } = useAIChat({
    apiKey,
    apiEndpoint,
    onThemeGenerated: handleThemeGenerated,
  });

  // No API key configured - show setup instructions
  if (!hasApiKey) {
    return (
      <div className="dm-ai-tool">
        <div className="dm-ai-setup-compact">
          <Sparkles size={24} className="dm-ai-setup-icon" />
          <div className="dm-ai-setup-text">
            <h4>API Key Required</h4>
            <p>
              Pass an OpenAI API key or custom endpoint to enable AI theme generation.
            </p>
          </div>
          <pre className="dm-code-block dm-code-small">
{`<DesignManager
  apiKey="sk-..."
/>`}
          </pre>
        </div>
        <div className="dm-ai-tool-actions">
          <button
            type="button"
            className="dm-button dm-button-secondary"
            onClick={onClose}
          >
            Close
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="dm-ai-tool">
      {/* Header with clear button */}
      {messages.length > 0 && (
        <div className="dm-ai-tool-header">
          <button
            type="button"
            className="dm-button dm-button-ghost dm-button-small"
            onClick={clearMessages}
          >
            <RefreshCw size={12} />
            New Chat
          </button>
        </div>
      )}

      {/* Quick prompts when empty */}
      {messages.length === 0 && (
        <div className="dm-ai-quick-prompts">
          {QUICK_PROMPTS.map((prompt, i) => (
            <button
              key={i}
              type="button"
              className="dm-ai-quick-chip"
              onClick={() => sendMessage(prompt)}
            >
              {prompt}
            </button>
          ))}
        </div>
      )}

      {/* Chat interface */}
      <AIChat
        messages={messages}
        onSend={sendMessage}
        onApplyTheme={handleApplyTheme}
        isLoading={isLoading}
        placeholder="Describe your theme..."
      />

      {/* Close button */}
      <div className="dm-ai-tool-actions">
        <button
          type="button"
          className="dm-button dm-button-secondary"
          onClick={onClose}
        >
          Close
        </button>
      </div>
    </div>
  );
}

export default AIThemeGenerator;
