/**
 * AI Tab
 *
 * AI-powered theme generation chat interface.
 */

import { useState, useCallback } from 'react';
import { Sparkles, RefreshCw } from 'lucide-react';
import { useAIChat } from '../hooks/useAIChat';
import { useDesignManagerContext } from '../context/DesignManagerContext';
import { AIChat } from '../components/ai/AIChat';

/**
 * Suggested prompts for inspiration
 */
const SUGGESTED_PROMPTS = [
  'Create a warm, cozy theme with earthy brown and amber tones',
  'Generate a modern minimal theme with cool blue accents',
  'Design a vibrant tropical theme with pink and teal',
  'Create a professional dark theme for a SaaS dashboard',
  'Make a soft pastel theme perfect for a wellness app',
  'Design a high-contrast accessible theme with purple tones',
];

export function AITab({ apiKey, apiEndpoint }) {
  const { importTheme, darkMode } = useDesignManagerContext();
  const [pendingTheme, setPendingTheme] = useState(null);

  /**
   * Handle theme application from AI response
   */
  const handleApplyTheme = useCallback((theme) => {
    if (!theme?.light || !theme?.dark) return;

    // Convert AI-generated colors to our format
    const themeData = {
      colors: {
        light: theme.light,
        dark: theme.dark,
      },
    };

    importTheme(themeData);
    setPendingTheme(null);
  }, [importTheme]);

  /**
   * Handle theme generated by AI (for preview)
   */
  const handleThemeGenerated = useCallback((theme) => {
    setPendingTheme(theme);
  }, []);

  const {
    messages,
    isLoading,
    sendMessage,
    clearMessages,
    hasApiKey,
  } = useAIChat({
    apiKey,
    apiEndpoint,
    onThemeGenerated: handleThemeGenerated,
  });

  // No API key configured
  if (!hasApiKey) {
    return (
      <div className="dm-tab-content dm-ai-tab">
        <div className="dm-tab-header">
          <h3 className="dm-tab-title">
            <Sparkles size={18} />
            AI Theme Generator
          </h3>
          <p className="dm-tab-description">
            Generate beautiful themes using AI.
          </p>
        </div>

        <div className="dm-ai-setup-card">
          <Sparkles size={32} className="dm-ai-setup-icon" />
          <h4>Setup Required</h4>
          <p>
            To use AI theme generation, provide an OpenAI API key or configure
            a custom API endpoint.
          </p>

          <div className="dm-ai-setup-options">
            <div className="dm-setup-option">
              <span className="dm-setup-label">Option 1: API Key</span>
              <pre className="dm-code-block">
{`<DesignManager
  apiKey="sk-..."
/>`}
              </pre>
            </div>

            <div className="dm-setup-option">
              <span className="dm-setup-label">Option 2: Custom Endpoint</span>
              <pre className="dm-code-block">
{`<DesignManager
  apiEndpoint="/api/design-manager/chat"
/>`}
              </pre>
            </div>
          </div>

          <p className="dm-ai-setup-note">
            Get your API key from{' '}
            <a
              href="https://platform.openai.com/api-keys"
              target="_blank"
              rel="noopener noreferrer"
            >
              platform.openai.com/api-keys
            </a>
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="dm-tab-content dm-ai-tab">
      <div className="dm-tab-header">
        <div className="dm-header-row">
          <div>
            <h3 className="dm-tab-title">
              <Sparkles size={18} />
              AI Theme Generator
            </h3>
            <p className="dm-tab-description">
              Describe your ideal theme and AI will generate it.
            </p>
          </div>

          {messages.length > 0 && (
            <button
              type="button"
              className="dm-button dm-button-secondary dm-button-small"
              onClick={clearMessages}
            >
              <RefreshCw size={12} />
              New Chat
            </button>
          )}
        </div>
      </div>

      {/* Suggested prompts */}
      {messages.length === 0 && (
        <div className="dm-ai-suggestions">
          <p className="dm-suggestions-label">Try one of these:</p>
          <div className="dm-suggestion-chips">
            {SUGGESTED_PROMPTS.map((prompt, i) => (
              <button
                key={i}
                type="button"
                className="dm-suggestion-chip"
                onClick={() => sendMessage(prompt)}
              >
                {prompt}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Chat interface */}
      <AIChat
        messages={messages}
        onSend={sendMessage}
        onApplyTheme={handleApplyTheme}
        isLoading={isLoading}
        placeholder="Describe your theme (e.g., warm and cozy with earth tones)..."
      />
    </div>
  );
}

export default AITab;
